#!/bin/bash
set -e
env=$(cat ~/.receipt-scan-serverless/$1/debug.env | paste -sd "," -)
if [ -z "${env}" ]; then
	envArg=""
else
	envArg="-E $env"
fi
echo "Waiting for gdb to attach..."
qemu-aarch64 -g 1234 -L /usr/sysroots/amazonlinux2-arm64/ $envArg build/$1/bin/$1 --debug -p events/$1.json