#!/bin/bash
set -e
export CONFIG=Release
yq '. *= load("template.release.yaml")' template.base.yaml > template.yaml
sam build
stackname=receipt-scan-$1
shift
sam deploy --confirm-changeset --stack-name $stackname $@ 
