#!/bin/bash
set -e
yq '. *= load("template.debug.yaml")' template.base.yaml > template.yaml
sam build --build-in-source
sudo sam local start-api \
  --host 0.0.0.0 \
  -n /usr/local/receipt-scan-serverless/debug.json
