AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless application for scanning and categorizing receipts

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Handler: bootstrap
    Runtime: provided.al2
    RuntimeManagementConfig:
      UpdateRuntimeOn: Manual
      RuntimeVersionArn: arn:aws:lambda:eu-central-1::runtime:c2f9d23694707c1161c0d3fbc0673f4ee14150265f4f3081161948aa71fad0a0
    Architectures:
      - arm64

Resources:
  RESTApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  ImagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain 

  FileUploader:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: file-uploader/
      Events:
        Api:
          Type: Api
          Properties:
            Path: /file
            Method: post
            RestApiId:
              Ref: RESTApi

